import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className={styles.title}>Tidycal bug reproduction</h1>
        <p>
          If you got to this page with client side navigation, the tidy cal navigation wont
          work.Perform a full browser refresh and then it will load
        </p>
        <p>
          If you got to directly to this page and tidycal did load, navigate to home page and then
          back here and tidycal wont load.
        </p>
        <div className={styles.grid}>
          <Link href='/'>
            <a className={styles.card}>
              <h2>Home</h2>
              <p>Go back to index</p>
            </a>
          </Link>
        </div>

        <div id='tidycal-embed' data-path='deedz/demo' />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
      <Script
        // strategy='beforeInteractive'
        id='tidycal'
        onLoad={evt => {
          console.log('tidyLoad', evt);
        }}
        src='https://asset-tidycal.b-cdn.net/js/embed.js'
      />
    </div>
  );
}
